# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import async_services_pb2 as async__services__pb2


class AsyncInferenceStub(object):
    """定义服务AsyncInference: 从机器人角度, 机器人将观察结果发送到并执行从远程策略服务器接收到的操作
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendObservations = channel.stream_unary(
                '/policy_service.AsyncInference/SendObservations',
                request_serializer=async__services__pb2.InferObservation.SerializeToString,
                response_deserializer=async__services__pb2.Empty.FromString,
                )
        self.GetActions = channel.unary_unary(
                '/policy_service.AsyncInference/GetActions',
                request_serializer=async__services__pb2.Empty.SerializeToString,
                response_deserializer=async__services__pb2.InferActions.FromString,
                )
        self.Ready = channel.unary_unary(
                '/policy_service.AsyncInference/Ready',
                request_serializer=async__services__pb2.Empty.SerializeToString,
                response_deserializer=async__services__pb2.Empty.FromString,
                )


class AsyncInferenceServicer(object):
    """定义服务AsyncInference: 从机器人角度, 机器人将观察结果发送到并执行从远程策略服务器接收到的操作
    """

    def SendObservations(self, request_iterator, context):
        """机器人 -> 与远程推理服务器共享观察结果的策略
        策略 ->  机器人共享针对给定观察结果预测的操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendObservations': grpc.stream_unary_rpc_method_handler(
                    servicer.SendObservations,
                    request_deserializer=async__services__pb2.InferObservation.FromString,
                    response_serializer=async__services__pb2.Empty.SerializeToString,
            ),
            'GetActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActions,
                    request_deserializer=async__services__pb2.Empty.FromString,
                    response_serializer=async__services__pb2.InferActions.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=async__services__pb2.Empty.FromString,
                    response_serializer=async__services__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy_service.AsyncInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsyncInference(object):
    """定义服务AsyncInference: 从机器人角度, 机器人将观察结果发送到并执行从远程策略服务器接收到的操作
    """

    @staticmethod
    def SendObservations(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/policy_service.AsyncInference/SendObservations',
            async__services__pb2.InferObservation.SerializeToString,
            async__services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/policy_service.AsyncInference/GetActions',
            async__services__pb2.Empty.SerializeToString,
            async__services__pb2.InferActions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/policy_service.AsyncInference/Ready',
            async__services__pb2.Empty.SerializeToString,
            async__services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
