# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async_services.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61sync_services.proto\x12\x0epolicy_service\"\x07\n\x05\x45mpty\"\x81\x01\n\x0eServerMetadata\x12>\n\x08metadata\x18\x01 \x03(\x0b\x32,.policy_service.ServerMetadata.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x10InferObservation\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"+\n\x0cInferActions\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xd9\x01\n\x0e\x41syncInference\x12M\n\x10SendObservations\x12 .policy_service.InferObservation\x1a\x15.policy_service.Empty(\x01\x12\x41\n\nGetActions\x12\x15.policy_service.Empty\x1a\x1c.policy_service.InferActions\x12\x35\n\x05Ready\x12\x15.policy_service.Empty\x1a\x15.policy_service.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERMETADATA_METADATAENTRY']._options = None
  _globals['_SERVERMETADATA_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=40
  _globals['_EMPTY']._serialized_end=47
  _globals['_SERVERMETADATA']._serialized_start=50
  _globals['_SERVERMETADATA']._serialized_end=179
  _globals['_SERVERMETADATA_METADATAENTRY']._serialized_start=132
  _globals['_SERVERMETADATA_METADATAENTRY']._serialized_end=179
  _globals['_INFEROBSERVATION']._serialized_start=181
  _globals['_INFEROBSERVATION']._serialized_end=213
  _globals['_INFERACTIONS']._serialized_start=215
  _globals['_INFERACTIONS']._serialized_end=258
  _globals['_ASYNCINFERENCE']._serialized_start=261
  _globals['_ASYNCINFERENCE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
