# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lerobot.transport import services_pb2 as lerobot_dot_transport_dot_services__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lerobot/transport/services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearnerServiceStub:
    """LearnerService: the Actor calls this to push transitions.
    The Learner implements this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamParameters = channel.unary_stream(
                '/transport.LearnerService/StreamParameters',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Parameters.FromString,
                _registered_method=True)
        self.SendTransitions = channel.stream_unary(
                '/transport.LearnerService/SendTransitions',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Transition.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.SendInteractions = channel.stream_unary(
                '/transport.LearnerService/SendInteractions',
                request_serializer=lerobot_dot_transport_dot_services__pb2.InteractionMessage.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/transport.LearnerService/Ready',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)


class LearnerServiceServicer:
    """LearnerService: the Actor calls this to push transitions.
    The Learner implements this service.
    """

    def StreamParameters(self, request, context):
        """Actor -> Learner to store transitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTransitions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInteractions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamParameters': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamParameters,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Parameters.SerializeToString,
            ),
            'SendTransitions': grpc.stream_unary_rpc_method_handler(
                    servicer.SendTransitions,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.Transition.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'SendInteractions': grpc.stream_unary_rpc_method_handler(
                    servicer.SendInteractions,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.InteractionMessage.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transport.LearnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearnerService:
    """LearnerService: the Actor calls this to push transitions.
    The Learner implements this service.
    """

    @staticmethod
    def StreamParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/transport.LearnerService/StreamParameters',
            lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Parameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTransitions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/transport.LearnerService/SendTransitions',
            lerobot_dot_transport_dot_services__pb2.Transition.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendInteractions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/transport.LearnerService/SendInteractions',
            lerobot_dot_transport_dot_services__pb2.InteractionMessage.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.LearnerService/Ready',
            lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AsyncInferenceStub:
    """AsyncInference: from Robot perspective
    Robot send observations to & executes action received from a remote Policy server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendObservations = channel.stream_unary(
                '/transport.AsyncInference/SendObservations',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Observation.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.GetActions = channel.unary_unary(
                '/transport.AsyncInference/GetActions',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Actions.FromString,
                _registered_method=True)
        self.SendPolicyInstructions = channel.unary_unary(
                '/transport.AsyncInference/SendPolicyInstructions',
                request_serializer=lerobot_dot_transport_dot_services__pb2.PolicySetup.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/transport.AsyncInference/Ready',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)


class AsyncInferenceServicer:
    """AsyncInference: 从机器人角度，机器人将观察结果发送到远程策略服务器并执行从远程策略服务器收到的操作
                        gRPC 服务端的基础骨架/接口模板，对应protobuf中 transport.AsyncInference 服务定义
                        这是一个 “待填充逻辑的空壳”，核心作用是对齐 gRPC 服务的方法定义，确保服务注册时方法名匹配，后续只需替换方法内的逻辑即可。
                        PolicyServer 类会继承该类并实现具体逻辑。
    """

    def SendObservations(self, request_iterator, context):
        """Robot -> Policy to share observations with a remote inference server
        Policy -> Robot to share actions predicted for given observations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPolicyInstructions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncInferenceServicer_to_server(servicer, server):
    '''
    把自定义的 AsyncInferenceServicer 服务实现注册到 gRPC 服务器，让客户端能调用对应的 RPC 方法

        核心作用: 打通 “二进制数据” 和 “Python 对象” 的转换
                客户端发送的二进制数据 → request_deserializer → 转成 Python 可处理的 Protobuf 对象；
                服务端返回的 Python 对象 → response_serializer → 转成二进制数据发给客户端；
                同时绑定 “方法名” 和 “处理函数”，让服务器知道 “收到 GetActions 请求时，调用 servicer.GetActions 处理”。

        servicer: 自定义的服务实现类实例（比如包含 SendObservations/GetActions 等方法的 AsyncInferenceServicer 类）；
        server: gRPC 服务器实例（比如 grpc.aio.server() 创建的异步服务器）
    '''

    # 构建 RPC 方法处理器字典 rpc_method_handlers: key是RPC方法名（与Protobuf定义的一致），value是该方法的处理器（指定处理函数、序列化 / 反序列化规则）
    rpc_method_handlers = {

        # grpc.stream_unary_rpc_method_handler：表示该方法是客户端流式RPC——客户端可以连续发送多个Observation请求，服务端处理完后返回一个Empty响应（比如客户端持续推送观测数据，服务端批量处理后确认）；
        # grpc.unary_unary_rpc_method_handler：最基础的 RPC 模式 —— 客户端发一个 Empty 请求，服务端返回一个 Actions 响应（比如客户端请求 “获取推理后的动作”，服务端返回动作数据）。
                # request_deserializer：把网络传输的二进制数据转成Protobuf定义的Observation类实例；
                # response_serializer：把服务端返回的Empty类实例转成二进制数据，用于网络传输。

            # SendObservations：流式请求 + 单响应（stream-unary）
            'SendObservations': grpc.stream_unary_rpc_method_handler(
                    servicer.SendObservations,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.Observation.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            # GetActions：单请求 + 单响应（unary-unary）
            'GetActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActions,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Actions.SerializeToString,
            ),
            # SendPolicyInstructions：单请求 + 单响应（unary-unary）
            'SendPolicyInstructions': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPolicyInstructions,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.PolicySetup.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            # Ready：单请求 + 单响应（unary-unary）
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
    }
    # 创建通用处理器并注册到服务器
        # 创建通用方法处理器，关联服务名（transport.AsyncInference）和方法处理器字典
        # transport.AsyncInference：是 Protobuf 中定义的服务名（对应 service AsyncInference { ... }），必须和 Protobuf 定义完全一致
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.AsyncInference', rpc_method_handlers)
        # 把通用处理器添加到服务器
    server.add_generic_rpc_handlers((generic_handler,))
        # 额外注册已定义的方法处理器（兼容不同gRPC版本的注册逻辑）
    server.add_registered_method_handlers('transport.AsyncInference', rpc_method_handlers)




 # This class is part of an EXPERIMENTAL API.


class AsyncInference:
    """AsyncInference: from Robot perspective
    Robot send observations to & executes action received from a remote Policy server
    """

    @staticmethod
    def SendObservations(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/transport.AsyncInference/SendObservations',
            lerobot_dot_transport_dot_services__pb2.Observation.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.AsyncInference/GetActions',
            lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Actions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPolicyInstructions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.AsyncInference/SendPolicyInstructions',
            lerobot_dot_transport_dot_services__pb2.PolicySetup.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.AsyncInference/Ready',
            lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lerobot_dot_transport_dot_services__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
